spring:
  application:
    name: geektime-ddd
  datasource:
    url: jdbc:mysql://localhost:3306/geektime-ddd?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: "root"

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl